# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-02 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('pctype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseid', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=50)),
                ('landlord_id', models.CharField(max_length=50)),
                ('org_id', models.EmailField(max_length=70)),
                ('name', models.CharField(max_length=50)),
                ('housestatus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=50)),
                ('realname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
                ('telephone', models.CharField(max_length=50)),
                ('right', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
