# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-02 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='idcard',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='district',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='realname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='right',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
